# main text of home
name: Joseph Hollowed
title: Joseph Hollowed
description: Personal website of Joseph Hollowed, serving professional and recreational works
picture: assets/images/picture.jpg
url: http://joehollowed.com

#connect
github: jhollowed
linkedin: joehollowed
email: jphollowed@gmail.com

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
