# main text of home
name: Joseph Hollowed
bio: Student in physics and researcher in cosmology

# twitter summary info
description: Personal website of Joe Hollowed

picture: assets/images/picture.jpg

url: http://joehollowed.com

# if you don't have any of social below, comment the line
#facebook: myfacebook
#twitter: mytwitter
github: https://github.com/jhollowed
#linkedin: https://www.linkedin.com/in/joehollowed/
email: jphollowed@gmail.com

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
