# main text of home
name: Joseph Hollowed
title: Joseph Hollowed
description: Personal website of Joseph Hollowed
picture: assets/images/picture.png
url: https://jhollowed.github.io/pages/

#connect
github: jhollowed
linkedin: joehollowed
email: hollowed@umich.edu

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site]
livereload: TRUE
