# main text of home
name: Joseph Hollowed
title: Joseph Hollowed
description: Personal website of Joseph Hollowed
picture: assets/images/picture.png
url: https://jhollowed.github.io/pages/

#connect
email: hollowed@umich.edu
github: jhollowed
orcid: 0000-0002-8658-1672
linkedin: joehollowed

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site]
livereload: TRUE
